repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: flake8
-   repo: git://github.com/luismayta/pre-commit-mypy
    rev: 'b9595c1'
    hooks:
    -   id: mypy
